//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package me.risky.jlike.controller;

import android.content.Context;
import org.androidannotations.api.BackgroundExecutor;

public final class NewsDetailController_
    extends NewsDetailController
{

    private Context context_;

    private NewsDetailController_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static NewsDetailController_ getInstance_(Context context) {
        return new NewsDetailController_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void load(final String url) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    NewsDetailController_.super.load(url);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

}
