//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package me.risky.jlike.controller;

import android.content.Context;

public final class NewsDetailController_
    extends NewsDetailController
{

    private Context context_;

    private NewsDetailController_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static NewsDetailController_ getInstance_(Context context) {
        return new NewsDetailController_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
