//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package me.risky.jlike.dao;

import android.content.Context;

public final class WelfareDao_
    extends WelfareDao
{

    private Context context_;

    private WelfareDao_(Context context) {
        context_ = context;
        init_();
    }

    public static WelfareDao_ getInstance_(Context context) {
        return new WelfareDao_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
