//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package me.risky.jlike.adapter;

import android.content.Context;

public final class NewsListAdapter_<T extends Object >
    extends NewsListAdapter<T>
{

    private Context context_;

    private NewsListAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static NewsListAdapter_ getInstance_(Context context) {
        return new NewsListAdapter_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
