package me.risky.jlike.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.risky.jlike.db.News;
import me.risky.jlike.db.Collection;

import me.risky.jlike.db.NewsDao;
import me.risky.jlike.db.CollectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsDaoConfig;
    private final DaoConfig collectionDaoConfig;

    private final NewsDao newsDao;
    private final CollectionDao collectionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        collectionDaoConfig = daoConfigMap.get(CollectionDao.class).clone();
        collectionDaoConfig.initIdentityScope(type);

        newsDao = new NewsDao(newsDaoConfig, this);
        collectionDao = new CollectionDao(collectionDaoConfig, this);

        registerDao(News.class, newsDao);
        registerDao(Collection.class, collectionDao);
    }
    
    public void clear() {
        newsDaoConfig.getIdentityScope().clear();
        collectionDaoConfig.getIdentityScope().clear();
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public CollectionDao getCollectionDao() {
        return collectionDao;
    }

}
