package me.risky.jlike.db;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS.
 */
public class News implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Long id;
    private String title;
    private String content;
    private String detailUrl;
    private String imageSrc;
    private String scanNum;
    private String dateTime;
    private Integer type;

    public News() {
    }

    public News(Long id) {
        this.id = id;
    }

    public News(Long id, String title, String content, String detailUrl, String imageSrc, String scanNum, String dateTime, Integer type) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.detailUrl = detailUrl;
        this.imageSrc = imageSrc;
        this.scanNum = scanNum;
        this.dateTime = dateTime;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getDetailUrl() {
        return detailUrl;
    }

    public void setDetailUrl(String detailUrl) {
        this.detailUrl = detailUrl;
    }

    public String getImageSrc() {
        return imageSrc;
    }

    public void setImageSrc(String imageSrc) {
        this.imageSrc = imageSrc;
    }

    public String getScanNum() {
        return scanNum;
    }

    public void setScanNum(String scanNum) {
        this.scanNum = scanNum;
    }

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
