//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package me.risky.jlike.bean;

import android.content.Context;

public final class Page_
    extends Page
{

    private Context context_;

    private Page_(Context context) {
        context_ = context;
        init_();
    }

    public static Page_ getInstance_(Context context) {
        return new Page_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
