//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package me.risky.jlike.bean;

import android.content.Context;

public final class WelfareItem_
    extends WelfareItem
{

    private Context context_;

    private WelfareItem_(Context context) {
        context_ = context;
        init_();
    }

    public static WelfareItem_ getInstance_(Context context) {
        return new WelfareItem_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
